### ISSUE TITLE
Setup testing environment for the mini-app in Telegram

### ISSUE THREAD

**Issue by kfastov** [kfastov/starbeam#2]
Figure out how testing environment in TG work, and write a detailed guide for future contributors on how to configure it.

Requirements:
- the guide, should be clear and complete
- an example on how you configured it for yourself

**Comment by josephchimebuka** [comment]
Can I handle this one?

**Comment by sonkeydotcom** [comment]
Hello, can I take this task

**Comment by sonkeydotcom** [comment]
I would like to take on this task to register the mini-app in Telegram and set up the testing environment. My approach includes creating the app registration, configuring the Telegram Bot API for the mini-app, and thoroughly researching and implementing the testing environment to ensure smooth functionality.  

With my experience in integrating third-party APIs, managing testing environments, and full-stack development, I am confident in delivering this task. If assigned, I can start immediately and complete it within 72hours, providing detailed documentation for future contributors.

**Comment by mimisavage** [comment]
Can I try solving this issue?

**Comment by Supa-mega** [comment]
I’d like to help with this. first time contributor ETA 24HRS

**Comment by Benjtalkshow** [comment]
Let me work on this please.

**Comment by wheval** [comment]
Mind if I try this one? 

ETA is 3 days.

**Comment by Jagadeeshftw** [comment]
Can I take care of this issue?

**Comment by josephchimebuka** [comment]
Thank you for assigning @kfastov I will get on with it RN
