### ISSUE TITLE
Fix build error caused by useLaunchParams()

### ISSUE THREAD

**Issue by kfastov** [kfastov/starbeam#5]
Currently I can't deploy the frontend placeholder to Vercel, because `yarn build` fails to pre-render main page without being opened in Telegram.
Find a way to resolve it while still maintaining the needed functionality and implement that fix
One of the ways is to move the mini-app main page under the separate route and leave a redirect on the main one

Requirements for the solution:
- `yarn build` should complete successfully
- Vercel action on Github should pass and lead to mini-app deployment
- No existing functionality should be affected

**Comment by Benjtalkshow** [comment]
I am a Full Stack Developer with a strong background in blockchain and extensive experience in Next.js/React, TypeScript, and Rust. I’ve made over 49 contributions to over 17 projects in the OnlyDust ecosystem, solving complex issues and delivering efficient, scalable solutions.

I can handle this task.
ETA is 3days.

**Comment by kfastov** [comment]
@Benjtalkshow Hi! Thank you for the interest, but I guess 3 days could be too much, because it's a bit urgent.
If you (or someone else) can do it faster (1-2 days), it would be great :)

**Comment by mimisavage** [comment]
May I handle this issue?

**Comment by Supa-mega** [comment]
Is it okay if I take this? first time contributor eta 24hrs

**Comment by Benjtalkshow** [comment]
I am a Full Stack Developer with a strong background in blockchain and extensive experience in Next.js/React, TypeScript, and Rust. I’ve made over 49 contributions to over 17 projects in the OnlyDust ecosystem, solving complex issues and delivering efficient, scalable solutions.

I can handle this task.
ETA is 3days.

**Comment by OWK50GA** [comment]
Hi, I'm Wilfrid Okorie, a Frontend Web Developer and I'd like to take this issue.

My approach:
I will try to replicate the issue by running yarn build. Then I will look closely to find the point of unwanted behaviour. After I find it, I will do appropriate research to see how it can be fixed, while ensuring not to break the needed functionality. 

If it is necessary, I would take the approach you mentioned in the issue description, by putting the mini-app in another route and leaving a redirect on the main page. 

Expect my first PR within 36 hours of assignment

**Comment by Benjtalkshow** [comment]
> @Benjtalkshow Hi! Thank you for the interest, but I guess 3 days could be too much, because it's a bit urgent.
> 
> If you (or someone else) can do it faster (1-2 days), it would be great :)

I can do it in two days. Kindly assign me the task. Thanks.

**Comment by Emmanex01** [comment]
Can I start working on this?
I'm Emmanuel Tochukwu, a software developer. I have experience debugging issues on projects. I would appreciate it if given the opportunity to contribute to this issue.

**Comment by Jagadeeshftw** [comment]
Can I take care of this issue?
