### ISSUE TITLE
Implement a factory smart contract

### ISSUE THREAD

**Issue by kfastov** [kfastov/starbeam#7]
Implement a factory smart contract that will verify telegram account ownership (using signature from #6 ) and deploy an account contract specifically for the telegram user who submitted this transaction.

It would be also good to maintain a mapping from telegram UIDs to account addresses, to allow account lookup with no need for backend or separate database

Possibly related resources:
- https://stellar.org/learn/crypto-smart-contract-wallets
- https://developers.stellar.org/docs/build/apps/smart-wallets#soroban-by-example-
- https://github.com/kalepail/soroban-passkey/tree/main/contracts

Requirements:
- new smart contract that builds and can be deployed
- can deploy accounts from #3 (may be replaced with a dummy contract if it's not ready yet)
- verifies signature and doesn't allow to deploy accounts with no ownership proof

**Comment by ShantelPeters** [comment]
Could I try solving this?

**Comment by mimisavage** [comment]
Can I jump on this task?

**Comment by manlikeHB** [comment]
Hi, I am a smart contract developer and also new to the stellar, I would like to work on this issue.

**Comment by wheval** [comment]
Can I attempt this issue?

ETA is 2 days.

**Comment by Emmanex01** [comment]
Mind if I try this one?
I'm Emmanuel Tochukwu, a software developer. I have experience building smart contract on Starknet. I would appreciate it if given the opportunity to contribute to this issue.

**Comment by Jagadeeshftw** [comment]
Can I be assigned to this?

**Comment by ryzen-xp** [comment]
Hi, I am proficient Blockchain developer  expert in Cairo , Rust and Solidity  and also in web development.
I have  contributed many cairo ,rust  projects like chainevents , arkprojects sunshine etc  .   please /assign  this issue .
Thank You
